-- AD-9 v1.1: the locker's public id becomes its primary key. The 25-char
-- cuid default is gone — ids are generated by the application as 6-char
-- values over the unambiguous pickup-code alphabet (no 0/O/1/I), so a
-- customer can type one one-handed.
--
-- Backfill: md5(id) is hex (0-9a-f), so `translate` remaps the two excluded
-- digits 0→2 and 1→3 — length-preserving, and the result stays inside the
-- alphabet {A-F, 2-9}. Deterministic per row; a collision among existing
-- rows would make the new primary key fail the migration loudly (dev-only
-- concern — fresh databases start with no rows).
--
-- Nothing references locker.id (the package link runs the other way:
-- locker.occupied_by → stored_package.id), so the swap touches one table.

ALTER TABLE "locker" DROP CONSTRAINT "locker_pkey";

UPDATE "locker"
SET "id" = upper(substring(translate(md5("id"), '01', '23') FROM 1 FOR 6));

ALTER TABLE "locker" ADD PRIMARY KEY ("id");
